version: '2.4'

services:

  flask:
    container_name: ${TOOL}-flask
    build:
      context: .
      dockerfile: flask.Dockerfile
      args:
        TOOL_NAME: ${TOOL}
    env_file: .env
    restart: always
    volumes:
      - ${DIR}/rest/src:/REST
      - ${DIR}/${TOOL}:/home/${TOOL}
      - ${DIR}/tofill/app:/REST/app

  redis:
    container_name: ${TOOL}-redis
    build:
      context: .
      dockerfile: redis.Dockerfile
      args:
        TOOL_NAME: ${TOOL}
    env_file: .env
    restart: always
    volumes:
      - ${DIR}/rest/src:/REST
      - ${DIR}/${TOOL}:/home/${TOOL}
      - ${DIR}/tofill/app:/REST/app


networks:
  default:
    name: ${TOOL}
