version: '2.4'

services:

  rest:
    image: ${TOOL}-rest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TOOL_NAME: ${TOOL}
    container_name: ${TOOL}-${MODE}
    restart: always
    environment:
      - REST_MODE=${MODE}
    volumes:
      - $PWD/rest/src:/REST
      - $PWD/${TOOL}:/home/${TOOL}
      - $PWD/tofill/app:/REST/app


networks:
  default:
    name: ${TOOL}
