version: '2.4'

services:

  rest:
    image: brsynth/${TOOL}-rest:${MODE}
    build:
      context: ..
      dockerfile: dockerfiles/${MODE}.dockerfile
      args:
        TOOL_NAME: ${TOOL}
    container_name: ${TOOL}-${MODE}
    restart: always
    environment:
      - REST_MODE=${MODE}
    volumes:
      - ${DIR}/rest/src:/REST
      - ${DIR}/${TOOL}:/home/${TOOL}
      - ${DIR}/app:/REST/app
      - ${DIR}/conf:/CONF


networks:
  default:
    name: ${TOOL}
