version: '2.4'

services:

  flask:
    container_name: ${TOOL}-flask
    build:
      context: .
      dockerfile: flask.Dockerfile
      args:
        TOOL_NAME: ${TOOL}
    env_file: flask.env
    restart: always
    volumes:
      - $PWD/rest/src:/REST
      - $PWD/${TOOL}:/home/${TOOL}
      - $PWD/tofill/app:/REST/app

  redis:
    container_name: ${TOOL}-redis
    build:
      context: .
      dockerfile: redis.Dockerfile
      args:
        DIR_NAME: ${DIR}
    env_file: redis.env
    restart: always
    volumes:
      - $PWD/rest/src:/REST
      - $PWD/${TOOL}:/home/${TOOL}
      - $PWD/tofill/app:/REST/app


networks:
  default:
    name: ${TOOL}
