#!/bin/bash

function print() {
  local msg=$1
  local msglen=${#msg}
#  banner=$(printf '%*s\n' "$((COLUMNS-2))" '' | tr ' ' '-')
  local banner=$(printf '%*s' $((msglen+2)) "" | tr ' ' '-')
  tput bold
  printf '\n'
  # printf '|'"$banner"'\n'
  # printf '| '"$msg"'\n'
  # printf '|'"$banner"'\n'
  printf "$msg"'\n'
  printf '\n'
  tput sgr0
}
